name: CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:  # Variables de entorno
  GREETING: "Hola, mundo desde GitHub Actions!"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Run a simple script
        run: echo $GREETING  # Usar la variable de entorno

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Run tests
        run: echo "Ejecutando pruebas..."

  deploy:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Deploy application
        run: echo "Desplegando la aplicación..."
